//------------------------------------------------------------------------------
// <auto-generated>
//     ?™æ®µç¨‹å?ç¢¼æ˜¯?±å·¥?·ç”¢?Ÿç???
//     ?·è??æ®µ?ˆæœ¬:2.0.50727.3603
//
//     å°é€™å€‹æ?æ¡ˆæ??šç?è®Šæ›´?¯èƒ½?ƒé€ æ??¯èª¤?„è??ºï??Œä?å¦‚æ??æ–°?¢ç?ç¨‹å?ç¢¼ï?
//     è®Šæ›´å°‡æ??ºå¤±??
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace BomCost.Flowwork {
    
    
    public class bomcost_2FlowNode1Reviewer {

        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments)
        {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USER = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USER = ht["USER"].ToString();

            }

            rc.Add(new System.Guid(USER.ToString()));

            return rc;
        }
    }
}
