//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace CusCon2.Flowwork {
    
    
    public class CusConFlow2Node1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            //rc.Add(new System.Guid("D45938A7-3430-42EC-8BE6-0E1F391329E0"));

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            string AppUid = ht["App"].ToString();
            rc.Add(new System.Guid(AppUid));
            return rc;
        }
    }
}
