//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace Education.Flowwork {
    
    
    public class Education_FlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode10Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'Kh.hsieh'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode11Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode12Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode13Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'sam.chiu'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode14Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'Kh.hsieh'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode15Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'sam.chiu'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode16Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'Kh.hsieh'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'yuhlin.wang'  or logonid ='lm.huang' or logonid ='elaine.chiu' or logonid ='yuhui.peng'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode6Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'yuhlin.wang'  or logonid ='lm.huang' or logonid ='elaine.chiu' or logonid ='yuhui.peng'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode7Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'yuhlin.wang'  or logonid ='lm.huang' or logonid ='elaine.chiu' or logonid ='yuhui.peng'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
    
    public class Education_FlowNode8Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class Education_FlowNode9Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("SELECT id FROM dguser WHERE  logonid = 'sam.chiu'");
            while (!ds.EOF)
            {
                rc.Add(new System.Guid(ds["id"].ToString()));
                ds.MoveNext();
            }
            return rc;
        }
    }
}
