//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace EHCos.Flowwork {
    
    
    public class EHCosFlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection Select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
           
            
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["App"].ToString();
            rc.Add(new System.Guid(AppUid));


            return rc;
        }
    }
    
    public class EHCosFlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["App2"].ToString();
            rc.Add(new System.Guid(AppUid));


            return rc;
        }
    }
}
