//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace EMP_ADD_SELECTUSER.Flowwork {
    
    
    public class EMP_ADD_SELECTUSER_FlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["SELECTUSER"].ToString();

            }


            rc.Add(new System.Guid(USERA));
            //    rc.Add(new System.Guid(USER));
            return rc;
        }
    }
    
    public class EMP_ADD_SELECTUSER_FlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERB = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERB = ht["USER"].ToString();

            }


            rc.Add(new System.Guid(USERB));
            //    rc.Add(new System.Guid(USER));
            return rc;
        }
    }

    public class EMP_ADD_SELECTUSER_FlowNode3Reviewer
    {

        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments)
        {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            //string USERB = "";
            //System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            //if (ht != null)
            //{
            //    USERB = ht["USER"].ToString();

            //}


            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E"));
            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4"));
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6"));
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01"));
            //    rc.Add(new System.Guid(USER));
            return rc;
        }
    }
}
