//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace employeeTraing.Flowwork {
    
    
    public class employeeTraingFlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER0"].ToString();
                USERTITLE = ht["USERTITLE0"].ToString();
            }
            rc.Add(new System.Guid(USERA));
            return rc;
        }
    }
    
    public class employeeTraingFlowNode10Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode11Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode12Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode13Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode14Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode15Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode16Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5"].ToString();
                USERTITLE = ht["USERTITLE5"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode17Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode18Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode19Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode20Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode21Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5"].ToString();
                USERTITLE = ht["USERTITLE5"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode22Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER6"].ToString();
                USERTITLE = ht["USERTITLE6"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode23Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode24Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode25Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode26Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode27Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5"].ToString();
                USERTITLE = ht["USERTITLE5"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode28Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER6"].ToString();
                USERTITLE = ht["USERTITLE6"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode29Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER7"].ToString();
                USERTITLE = ht["USERTITLE7"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode30Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode31Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode32Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode33Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode34Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5"].ToString();
                USERTITLE = ht["USERTITLE5"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode35Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER6"].ToString();
                USERTITLE = ht["USERTITLE6"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode36Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER7"].ToString();
                USERTITLE = ht["USERTITLE7"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode37Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER8"].ToString();
                USERTITLE = ht["USERTITLE8"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode38Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode39Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode40Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode41Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4"].ToString();
                USERTITLE = ht["USERTITLE4"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode42Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5"].ToString();
                USERTITLE = ht["USERTITLE5"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode43Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER6"].ToString();
                USERTITLE = ht["USERTITLE6"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode44Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER7"].ToString();
                USERTITLE = ht["USERTITLE7"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode45Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER8"].ToString();
                USERTITLE = ht["USERTITLE8"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode46Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER9"].ToString();
                USERTITLE = ht["USERTITLE9"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode6Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode7Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3"].ToString();
                USERTITLE = ht["USERTITLE3"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode8Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1"].ToString();
                USERTITLE = ht["USERTITLE1"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
    
    public class employeeTraingFlowNode9Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection SelectUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2"].ToString();
                USERTITLE = ht["USERTITLE2"].ToString();

                if (USERA == "人事F4")
                {
                    SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
                    ds.Open("SELECT id FROM dguser WHERE   logonid ='yuhui.peng'");
                    while (!ds.EOF)
                    {
                        rc.Add(new System.Guid(ds["id"].ToString()), USERTITLE);
                        ds.MoveNext();
                    }

                }
                else
                {
                    rc.Add(new System.Guid(USERA), USERTITLE);
                }

            }
            return rc;
        }
    }
}
