//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;

namespace HRl.Flowwork {
    
    
    public class LeaveFlow_lv6Node1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            rc.Add(new System.Guid(ht["MAP"].ToString()));    //ª½ÄÝ¥DºÞ
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class LeaveFlow_lv6Node2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            int app_c = Convert.ToInt32(ht["apnum"]);

            for (int i = 1; i <= app_c; i++)
            {
                string pud = "AP" + i.ToString();

                if (ht[pud].ToString() != null)
                {
                    //app_c = app_c + 1;
                    //string AppUid = ht[pud].ToString();
                    rc.Add(new System.Guid(ht[pud].ToString()));      //¸ó³¡ªù¥DºÞ
                    //rc.Add(new System.Guid(AppUid));
                }
            }
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class LeaveFlow_lv6Node3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            //rc.Add(new System.Guid("394B5EEA-4DA5-4E2A-874C-F2047D0D4DEF")); //¼B©¯»ö
            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4")); //¶ÀÄR±ö
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E")); //ªôÚ{¯ø
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6")); //¤ý¥É¬Â
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01")); //´^¥É´f

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
}
