//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace Pro.Flowwork {
    
    
    public class MAProFlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["App"].ToString();
            rc.Add(new System.Guid(AppUid));
            return rc;
        }
    }
    
    public class MAProFlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["CMIS"].ToString();
            rc.Add(new System.Guid(AppUid));
            return rc;
        }
    }
    
    public class MAProFlowNode3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            rc.Add(new System.Guid("B76FC2D3-7910-4641-A51B-8B6023C567AE"));
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class MAProFlowNode4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            //根據Flow Parameter中所設定的參數, 決定第三關審核人
            string CustomNode3Approver = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter, "CustomNode3Approver");

            if (ht != null)
            {
                CustomNode3Approver = ht["CustomNode3Approver"].ToString();
                if (CustomNode3Approver != "")
                {
                    rc.Add(new System.Guid(CustomNode3Approver));
                }
            }


            return rc;

        }
    }
}
