//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Data.SqlClient;

namespace MASec2.Flowwork {
    
    
    public class MASec2FlowNode1Reviewer {
        /*public static string oradb = System.Web.Configuration.WebConfigurationManager.ConnectionStrings["EIPAConnectionString"].ConnectionString;

        private void acttable(string sql)
        {
            SqlConnection conn1 = new SqlConnection(oradb);
            conn1.Open();

            SqlCommand ccom1 = new SqlCommand(sql, conn1);

            ccom1.ExecuteNonQuery();
            conn1.Close();

        }
        */


        //子廠主管
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CMessage(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
           
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            string AppUid = ht["App"].ToString();


           // string sq3 = "insert into  misbuffer2(caption)values('" + AppUid + "')";
           // acttable(sq3);


            rc.Add(new System.Guid(AppUid));
            return rc;
        }
    }

    public class MASec2FlowNode2Reviewer : System.Web.UI.Page
    {
        //子廠MIS
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CMIS(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            Uri uri = HttpContext.Current.Request.Url;
            string linkvalue = uri.PathAndQuery;
            string remark = "";

            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            ds.Open("select TOP (1)  caption,id from   misbuffer where requesturl='" + linkvalue + "' order by  id desc");
            if (!ds.EOF) rc.Add(new System.Guid(ds["caption"].ToString()));
            return rc;
        }
    }
    
    public class MASec2FlowNode3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection MAO(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            string AppUid = ht["Test1"].ToString();
            if (AppUid == "Test1")
            {
                //內稽 呂小姐
                rc.Add(new System.Guid("7DB79DC2-424C-4ACC-9E42-DBADDB93E043"));
            }
            else
            {
                rc.Add(new System.Guid(AppUid));
            }
            return rc;
        }
    }

    public class MASec2FlowNode4Reviewer : System.Web.UI.Page
    {
        //總公司MIS主管
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection MAMIS(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            
            

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            SmoothEnterprise.Database.DataSet ds = new SmoothEnterprise.Database.DataSet();
            string AppUid = ht["Test2"].ToString();
            if (AppUid == "Test2")
            {
                //總公司MIS主管
                rc.Add(new System.Guid("B76FC2D3-7910-4641-A51B-8B6023C567AE"));
            
            }
            else
            {
                rc.Add(new System.Guid(AppUid));
            }
            return rc;

               
        }
    }
    
    public class MASec2FlowNode5Reviewer {
        //總公司MIS成員
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection MISO(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            string CustomNode3Approver = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter, "CustomNode3Approver");

            if (ht != null)
            {
                CustomNode3Approver = ht["CustomNode3Approver"].ToString();
                if (CustomNode3Approver != "")
                {
                    rc.Add(new System.Guid(CustomNode3Approver));
                }
            }
            return rc;
        }
    }
}
