//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace MAT.HR.Flowwork {
    
    
    public class MNode1_1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER1_1"].ToString();
                USERTITLE = ht["USERTITLE1_1"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode2_1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            string USERA0 = "";
            string USERTITLE0 = "";
            string USERA1 = "";
            string USERTITLE1 = "";
            string USERA2 = "";
            string USERTITLE2 = "";


            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA0 = ht["USER2_1_0"].ToString();
                USERTITLE0 = ht["USERTITLE2_1_0"].ToString();
            }


            if (ht != null)
            {
                USERA1 = ht["USER2_1_1"].ToString();
                USERTITLE1 = ht["USERTITLE2_1_1"].ToString();
            }

            if (ht != null)
            {
                USERA2 = ht["USER2_1_2"].ToString();
                USERTITLE2 = ht["USERTITLE2_1_2"].ToString();
            }


            rc.Add(new System.Guid(USERA0), USERTITLE0);
            if (USERA1 != "") { rc.Add(new System.Guid(USERA1), USERTITLE1); }
            if (USERA2 != "") { rc.Add(new System.Guid(USERA2), USERTITLE2); }


            return rc;
        }
    }
    
    public class MNode2_2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
           /* string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER2_2"].ToString();
                USERTITLE = ht["USERTITLE2_2"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE); */
           
            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4"),"人事"); //黃麗梅
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E"), "人事"); //邱琬茹
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6"), "人事"); //王玉玲
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01"), "人事"); //彭玉惠

            return rc;
        }
    }
    
    public class MNode3_1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA0 = "";
            string USERTITLE0 = "";
            string USERA1 = "";
            string USERTITLE1 = "";
            string USERA2 = "";
            string USERTITLE2 = "";


            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA0 = ht["USER3_1_0"].ToString();
                USERTITLE0 = ht["USERTITLE3_1_0"].ToString();
            }


            if (ht != null)
            {
                USERA1 = ht["USER3_1_1"].ToString();
                USERTITLE1 = ht["USERTITLE3_1_1"].ToString();
            }

            if (ht != null)
            {
                USERA2 = ht["USER3_1_2"].ToString();
                USERTITLE2 = ht["USERTITLE3_1_2"].ToString();
            }


            rc.Add(new System.Guid(USERA0), USERTITLE0);
            if (USERA1 != "") { rc.Add(new System.Guid(USERA1), USERTITLE1); }
            if (USERA2 != "") { rc.Add(new System.Guid(USERA2), USERTITLE2); }


            return rc;
        }
    }
    
    public class MNode3_2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3_2"].ToString();
                USERTITLE = ht["USERTITLE3_2"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode3_3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
          /*  string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER3_3"].ToString();
                USERTITLE = ht["USERTITLE3_3"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE); */


            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4"), "人事"); //黃麗梅
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E"), "人事"); //邱琬茹
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6"), "人事"); //王玉玲
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01"), "人事"); //彭玉惠

            return rc;
        }
    }
    
    public class MNode4_1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA0 = "";
            string USERTITLE0 = "";
            string USERA1 = "";
            string USERTITLE1 = "";
            string USERA2 = "";
            string USERTITLE2 = "";


            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA0 = ht["USER4_1_0"].ToString();
                USERTITLE0 = ht["USERTITLE4_1_0"].ToString();
            }
            

           if (ht != null)
            {
                USERA1 = ht["USER4_1_1"].ToString();
                USERTITLE1 = ht["USERTITLE4_1_1"].ToString();
            }

            if (ht != null)
            {
                USERA2 = ht["USER4_1_2"].ToString();
                USERTITLE2 = ht["USERTITLE4_1_2"].ToString();
            }

            
            rc.Add(new System.Guid(USERA0), USERTITLE0);
            if (USERA1!="") { rc.Add(new System.Guid(USERA1), USERTITLE1); }
            if (USERA2!="") { rc.Add(new System.Guid(USERA2), USERTITLE2); }
            
            return rc;
        }
    }
    
    public class MNode4_2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4_2"].ToString();
                USERTITLE = ht["USERTITLE4_2"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode4_3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4_3"].ToString();
                USERTITLE = ht["USERTITLE4_3"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode4_4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
           /* string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER4_4"].ToString();
                USERTITLE = ht["USERTITLE4_4"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE); */

            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4"), "人事"); //黃麗梅
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E"), "人事"); //邱琬茹
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6"), "人事"); //王玉玲
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01"), "人事"); //彭玉惠

            return rc;
        }
    }
    
    public class MNode5_1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA0 = "";
            string USERTITLE0 = "";
            string USERA1 = "";
            string USERTITLE1 = "";
            string USERA2 = "";
            string USERTITLE2 = "";


            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA0 = ht["USER5_1_0"].ToString();
                USERTITLE0 = ht["USERTITLE5_1_0"].ToString();
            }


            if (ht != null)
            {
                USERA1 = ht["USER5_1_1"].ToString();
                USERTITLE1 = ht["USERTITLE5_1_1"].ToString();
            }

            if (ht != null)
            {
                USERA2 = ht["USER5_1_2"].ToString();
                USERTITLE2 = ht["USERTITLE5_1_2"].ToString();
            }


            rc.Add(new System.Guid(USERA0), USERTITLE0);
            if (USERA1 != "") { rc.Add(new System.Guid(USERA1), USERTITLE1); }
            if (USERA2 != "") { rc.Add(new System.Guid(USERA2), USERTITLE2); }
            return rc;
        }
    }
    
    public class MNode5_2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5_2"].ToString();
                USERTITLE = ht["USERTITLE5_2"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode5_3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5_3"].ToString();
                USERTITLE = ht["USERTITLE5_3"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode5_4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5_4"].ToString();
                USERTITLE = ht["USERTITLE5_4"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE);
            return rc;
        }
    }
    
    public class MNode5_5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
           /* string USERA = "";
            string USERTITLE = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            if (ht != null)
            {
                USERA = ht["USER5_5"].ToString();
                USERTITLE = ht["USERTITLE5_5"].ToString();
            }
            rc.Add(new System.Guid(USERA), USERTITLE); */

            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4"), "人事"); //黃麗梅
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E"), "人事"); //邱琬茹
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6"), "人事"); //王玉玲
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01"), "人事"); //彭玉惠

            return rc;
        }
    }
}
