//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace ModERPF2.Flowwork {
    
    
    public class ModERP2FlowNode1Reviewer {
        //單位主管
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["App"].ToString();
            rc.Add(new System.Guid(AppUid));

            return rc;
        }
    }
    
    public class ModERP2FlowNode2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["ACC1"].ToString();
            rc.Add(new System.Guid(AppUid));


            return rc;
        }
    }
    
    public class ModERP2FlowNode3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["ACC2"].ToString();
            rc.Add(new System.Guid(AppUid));
            
            return rc;
        }
    }
    
    public class ModERP2FlowNode4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();
            // Put your code to generate custom reviewers
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;
            string AppUid = ht["MIS"].ToString();
            rc.Add(new System.Guid(AppUid)); // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            
            return rc;
        }
    }
    
    public class ModERP2FlowNode5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection select(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();


            string CustomNode3Approver = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter, "CustomNode3Approver");

            if (ht != null)
            {
                CustomNode3Approver = ht["CustomNode3Approver"].ToString();
                if (CustomNode3Approver != "")
                {
                    rc.Add(new System.Guid(CustomNode3Approver));
                }
            }
            
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
}
