//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;

namespace HRonew.Flowwork {
    
    
    public class OutFlow_c4Node1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection PopupUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            rc.Add(new System.Guid(ht["MAP"].ToString()));
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_c4Node2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            rc.Add(new System.Guid(ht["GPU"].ToString()));
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_c4Node3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            int app_c = Convert.ToInt32(ht["apmn"]);

            for (int i = 1; i <= app_c; i++)
            {
                string pud = "APM" + i.ToString();

                if (ht[pud].ToString() != null)
                {
                    rc.Add(new System.Guid(ht[pud].ToString()));
                }
            }
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_c4Node4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            rc.Add(new System.Guid("0D87783E-0547-4536-8466-4D541A575817")); //ªô¥ÃªL
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_c4Node5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4")); //¶ÀÄR±ö
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E")); //ªôÚ{¯ø
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6")); //¤ý¥É¬Â
            rc.Add(new System.Guid("C0B9B4E4-312F-4282-9549-7651A830AD01")); //´^¥É´f
            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
}
