//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;

namespace HRo2.Flowwork {
    
    
    public class OutFlow_sc1Node1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection PopupUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            rc.Add(new System.Guid(ht["MAP"].ToString()));

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_sc1Node2Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            //int app_c = 0;

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            //rc.Add(new System.Guid(ht["AP1"].ToString()));
            //rc.Add(new System.Guid(ht["AP2"].ToString()));
            //rc.Add(new System.Guid(ht["AP3"].ToString()));
            //rc.Add(new System.Guid(ht["AP4"].ToString()));
            //rc.Add(new System.Guid(ht["AP5"].ToString()));

            int app_c = Convert.ToInt32(ht["apnum"]);

            for (int i = 1; i <= app_c; i++)
            {
                string pud = "AP" + i.ToString();

                if (ht[pud].ToString() != null)
                {
                    //app_c = app_c + 1;
                    //string AppUid = ht[pud].ToString();
                    rc.Add(new System.Guid(ht[pud].ToString()));
                    //rc.Add(new System.Guid(AppUid));
                }
            }

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_sc1Node3Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            rc.Add(new System.Guid(ht["GPU"].ToString()));

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_sc1Node4Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            int app_c = Convert.ToInt32(ht["apmn"]);

            for (int i = 1; i <= app_c; i++)
            {
                string pud = "APM" + i.ToString();

                if (ht[pud].ToString() != null)
                {
                    rc.Add(new System.Guid(ht[pud].ToString()));
                }
            }

            //rc.Add(new System.Guid(ht["APM1"].ToString()));

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
    
    public class OutFlow_sc1Node5Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection CustomUser(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            //rc.Add(new System.Guid("608B09C6-8525-4907-9227-1AE107B14C8E")); //ªLªY¯ø
            //rc.Add(new System.Guid("D45938A7-3430-42EC-8BE6-0E1F391329E0")); //ªL®¶»¨
            //rc.Add(new System.Guid("394B5EEA-4DA5-4E2A-874C-F2047D0D4DEF")); //¼B©¯»ö
            rc.Add(new System.Guid("69EBD7A2-F22D-4A25-8D84-C97C43D1B0C4")); //¶ÀÄR±ö
            rc.Add(new System.Guid("569AE95D-877F-4880-838D-0D6D4BCF277E")); //ªôÚ{¯ø
            rc.Add(new System.Guid("DC62DBEB-6268-4254-B8ED-191DD35587C6")); //¤ý¥É¬Â

            // Put your code to generate custom reviewers
            // Example :
            // rc.Add(userid);
            // rc.Add(userid,text);
            //  
            // Get parameter value(s)
            // Example :
            // object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter,key);
            return rc;
        }
    }
}
