//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This class library contains all the custom flow reviewer generating logic(s)
namespace RBQ.Flowwork {
    
    
    public class RBQFlowNode1Reviewer {
        
        public virtual SmoothEnterprise.Flowwork.Control.FlowReviewerCollection customer(System.Guid requestuid, object parameter, object arguments) {
            SmoothEnterprise.Flowwork.Control.FlowReviewerCollection rc = new SmoothEnterprise.Flowwork.Control.FlowReviewerCollection();

            string uid = "";
            System.Collections.Hashtable ht = parameter as System.Collections.Hashtable;

            object value = SmoothEnterprise.Flowwork.Control.FlowReviewer.GetParameter(parameter, "CustomNode3Approver");

            uid = ht["KID"].ToString();
                 
            rc.Add(new System.Guid(uid));
                
             

            return rc;
        }
    }
}
