<%@ Page Language="C#" MasterPageFile="~/_site/layout/Template.master" AutoEventWireup="true" CodeFile="ERP_APMI255Add.aspx.cs" Inherits="ERP_APMI255.ERP_APMI255Add" StylesheetTheme="Default" Culture="Auto" UICulture="Auto"%>
<%@ Register Assembly="SmoothEnterprise.Web.Control, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2bc4b50aa8c436e1"
    Namespace="SmoothEnterprise.Web.UI.HTMLControl" TagPrefix="SmoothEnterpriseWebControl" %>
<%@ Register Assembly="SmoothEnterprise.Web.Control.Enterprise, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2bc4b50aa8c436e1"
    Namespace="SmoothEnterprise.Content.UI.WebControl" TagPrefix="SmoothEnterpriseWebControlEnterprise" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <SmoothEnterpriseWebControlEnterprise:Descriptor ID="ContentDescriptor" runat="server" Details="The desciption for this program"
		Caption="ERP_APMI255 Add Page" Width="100%" CssClass="Normal" Gradient="None" Height="40%" PaddingSpace="5px">
		<CaptionStyle Font-Bold="True" CssClass="Medium"></CaptionStyle>
		<DetailsStyle Font-Size="11px" Font-Names="Arial" ForeColor="Gray"></DetailsStyle>
    </SmoothEnterpriseWebControlEnterprise:Descriptor>
	<table border="0" Class="Normal">
		<tr>
			<td valign="top">
				<table>
					
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_no" runat="server" CssClass="NormalBold" Text="No"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_no" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「No」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_plantid" runat="server" CssClass="NormalBold" Text="Plantid"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_plantid" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Plantid」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_CompanyName" runat="server" CssClass="NormalBold" Text="CompanyName"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_CompanyName" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「CompanyName」!!" MaxLength="50"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi01" runat="server" CssClass="NormalBold" Text="Pmi01"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi01" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi01」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi02" runat="server" CssClass="NormalBold" Text="Pmi02"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi02" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi02」!!" MaxLength="0"  FormatType="DateTime"><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi03" runat="server" CssClass="NormalBold" Text="Pmi03"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi03" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi03」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmc03_0" runat="server" CssClass="NormalBold" Text="Pmc03_0"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmc03_0" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmc03_0」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi04" runat="server" CssClass="NormalBold" Text="Pmi04"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi04" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi04」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi05" runat="server" CssClass="NormalBold" Text="Pmi05"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi05" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi05」!!" MaxLength="5"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi06" runat="server" CssClass="NormalBold" Text="Pmi06"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi06" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi06」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi07" runat="server" CssClass="NormalBold" Text="Pmi07"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi07" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi07」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi08" runat="server" CssClass="NormalBold" Text="Pmi08"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi08" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi08」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmi081" runat="server" CssClass="NormalBold" Text="Pmi081"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmi081" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmi081」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmiuser" runat="server" CssClass="NormalBold" Text="Pmiuser"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmiuser" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmiuser」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_gen02_1" runat="server" CssClass="NormalBold" Text="Gen02_1"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_gen02_1" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Gen02_1」!!" MaxLength="30"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_pmigrup" runat="server" CssClass="NormalBold" Text="Pmigrup"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_pmigrup" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Pmigrup」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_gem02_2" runat="server" CssClass="NormalBold" Text="Gem02_2"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_gem02_2" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Gem02_2」!!" MaxLength="40"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_flowstatus" runat="server" CssClass="NormalBold" Text="Flowstatus"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_flowstatus" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Flowstatus」!!" MaxLength="0"  FormatType="Number"><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_quick" runat="server" CssClass="NormalBold" Text="Quick"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_quick" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Quick」!!" MaxLength="5"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_lsend" runat="server" CssClass="NormalBold" Text="Lsend"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_lsend" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Lsend」!!" MaxLength="0"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_mpru" runat="server" CssClass="NormalBold" Text="Mpru"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_mpru" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Mpru」!!" MaxLength="0"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_senduser" runat="server" CssClass="NormalBold" Text="Senduser"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_senduser" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Senduser」!!" MaxLength="0"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_rember" runat="server" CssClass="NormalBold" Text="Rember"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_rember" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Rember」!!" MaxLength="200"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_status" runat="server" CssClass="NormalBold" Text="Status"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_status" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Status」!!" MaxLength="5"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
				</table>
			</td>
		</tr>
	</table>
	<table border="0" Class="Normal">
		<tr>
			<td>
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_save" runat="server" Text="儲存" width="80px" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_save_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>&nbsp;
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_savenext" runat="server" Text="儲存後繼續操作" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_save_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>&nbsp;
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_back" runat="server" Text="回上頁" width="80px" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_back_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>
			</td>
		</tr>
	</table>
</asp:Content>