<%@ Page Language="C#" MasterPageFile="~/_site/layout/Template.master" AutoEventWireup="true" CodeFile="ERP_AXMI25Add.aspx.cs" Inherits="CNE.CNEAdd" StylesheetTheme="Default" Culture="Auto" UICulture="Auto"%>
<%@ Register Assembly="SmoothEnterprise.Web.Control, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2bc4b50aa8c436e1"
    Namespace="SmoothEnterprise.Web.UI.HTMLControl" TagPrefix="SmoothEnterpriseWebControl" %>
<%@ Register Assembly="SmoothEnterprise.Web.Control.Enterprise, Version=2.0.0.0, Culture=neutral, PublicKeyToken=2bc4b50aa8c436e1"
    Namespace="SmoothEnterprise.Content.UI.WebControl" TagPrefix="SmoothEnterpriseWebControlEnterprise" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <SmoothEnterpriseWebControlEnterprise:Descriptor ID="ContentDescriptor" runat="server" Details="The desciption for this program"
		Caption="CNE Add Page" Width="100%" CssClass="Normal" Gradient="None" Height="40%" PaddingSpace="5px">
		<CaptionStyle Font-Bold="True" CssClass="Medium"></CaptionStyle>
		<DetailsStyle Font-Size="11px" Font-Names="Arial" ForeColor="Gray"></DetailsStyle>
    </SmoothEnterpriseWebControlEnterprise:Descriptor>
	<table border="0" Class="Normal">
		<tr>
			<td valign="top">
				<table>
					
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa01" runat="server" CssClass="NormalBold" Text="Occa01"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa01" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa01」!!" MaxLength="10" Required="True" ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa36" runat="server" CssClass="NormalBold" Text="Occa36"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa36" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa36」!!" MaxLength="0"  FormatType="Number"><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa37" runat="server" CssClass="NormalBold" Text="Occa37"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa37" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa37」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa61" runat="server" CssClass="NormalBold" Text="Occa61"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa61" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa61」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa63" runat="server" CssClass="NormalBold" Text="Occa63"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa63" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa63」!!" MaxLength="0"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa06" runat="server" CssClass="NormalBold" Text="Ta_occa06"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa06" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa06」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa07" runat="server" CssClass="NormalBold" Text="Ta_occa07"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa07" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa07」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_argv2" runat="server" CssClass="NormalBold" Text="Argv2"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_argv2" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Argv2」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa00" runat="server" CssClass="NormalBold" Text="Occa00"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa00" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa00」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occano" runat="server" CssClass="NormalBold" Text="Occano"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occano" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occano」!!" MaxLength="40" Required="True" ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa02" runat="server" CssClass="NormalBold" Text="Occa02"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa02" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa02」!!" MaxLength="40"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa03" runat="server" CssClass="NormalBold" Text="Occa03"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa03" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa03」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa04" runat="server" CssClass="NormalBold" Text="Occa04"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa04" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa04」!!" MaxLength="8"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa06" runat="server" CssClass="NormalBold" Text="Occa06"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa06" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa06」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa07" runat="server" CssClass="NormalBold" Text="Occa07"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa07" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa07」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa08" runat="server" CssClass="NormalBold" Text="Occa08"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa08" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa08」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa09" runat="server" CssClass="NormalBold" Text="Occa09"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa09" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa09」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa11" runat="server" CssClass="NormalBold" Text="Occa11"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa11" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa11」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa12" runat="server" CssClass="NormalBold" Text="Occa12"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa12" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa12」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa13" runat="server" CssClass="NormalBold" Text="Occa13"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa13" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa13」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa14" runat="server" CssClass="NormalBold" Text="Occa14"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa14" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa14」!!" MaxLength="20"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa15" runat="server" CssClass="NormalBold" Text="Occa15"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa15" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa15」!!" MaxLength="0"  FormatType="Number"><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa18" runat="server" CssClass="NormalBold" Text="Occa18"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa18" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa18」!!" MaxLength="80"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa19" runat="server" CssClass="NormalBold" Text="Occa19"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa19" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa19」!!" MaxLength="80"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa20" runat="server" CssClass="NormalBold" Text="Occa20"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa20" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa20」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa21" runat="server" CssClass="NormalBold" Text="Occa21"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa21" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa21」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa23" runat="server" CssClass="NormalBold" Text="Occa23"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa23" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa23」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa24" runat="server" CssClass="NormalBold" Text="Occa24"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa24" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa24」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa261" runat="server" CssClass="NormalBold" Text="Occa261"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa261" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa261」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa262" runat="server" CssClass="NormalBold" Text="Occa262"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa262" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa262」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa263" runat="server" CssClass="NormalBold" Text="Occa263"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa263" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa263」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa271" runat="server" CssClass="NormalBold" Text="Occa271"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa271" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa271」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa272" runat="server" CssClass="NormalBold" Text="Occa272"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa272" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa272」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa273" runat="server" CssClass="NormalBold" Text="Occa273"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa273" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa273」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa28" runat="server" CssClass="NormalBold" Text="Occa28"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa28" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa28」!!" MaxLength="30"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa29" runat="server" CssClass="NormalBold" Text="Occa29"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa29" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa29」!!" MaxLength="150"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa292" runat="server" CssClass="NormalBold" Text="Occa292"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa292" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa292」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa30" runat="server" CssClass="NormalBold" Text="Occa30"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa30" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa30」!!" MaxLength="150"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa302" runat="server" CssClass="NormalBold" Text="Occa302"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa302" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa302」!!" MaxLength="15"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa33" runat="server" CssClass="NormalBold" Text="Occa33"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa33" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa33」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa35" runat="server" CssClass="NormalBold" Text="Occa35"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa35" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa35」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa38" runat="server" CssClass="NormalBold" Text="Occa38"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa38" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa38」!!" MaxLength="2"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa39" runat="server" CssClass="NormalBold" Text="Occa39"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa39" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa39」!!" MaxLength="2"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa41" runat="server" CssClass="NormalBold" Text="Occa41"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa41" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa41」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa42" runat="server" CssClass="NormalBold" Text="Occa42"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa42" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa42」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa43" runat="server" CssClass="NormalBold" Text="Occa43"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa43" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa43」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa44" runat="server" CssClass="NormalBold" Text="Occa44"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa44" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa44」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa45" runat="server" CssClass="NormalBold" Text="Occa45"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa45" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa45」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa46" runat="server" CssClass="NormalBold" Text="Occa46"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa46" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa46」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa47" runat="server" CssClass="NormalBold" Text="Occa47"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa47" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa47」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa48" runat="server" CssClass="NormalBold" Text="Occa48"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa48" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa48」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa49" runat="server" CssClass="NormalBold" Text="Occa49"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa49" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa49」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa50" runat="server" CssClass="NormalBold" Text="Occa50"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa50" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa50」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa51" runat="server" CssClass="NormalBold" Text="Occa51"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa51" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa51」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa55" runat="server" CssClass="NormalBold" Text="Occa55"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa55" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa55」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa56" runat="server" CssClass="NormalBold" Text="Occa56"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa56" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa56」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa62" runat="server" CssClass="NormalBold" Text="Occa62"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa62" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa62」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa631" runat="server" CssClass="NormalBold" Text="Occa631"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa631" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa631」!!" MaxLength="4"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa701" runat="server" CssClass="NormalBold" Text="Occa701"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa701" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa701」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa702" runat="server" CssClass="NormalBold" Text="Occa702"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa702" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa702」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa703" runat="server" CssClass="NormalBold" Text="Occa703"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa703" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa703」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa704" runat="server" CssClass="NormalBold" Text="Occa704"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa704" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa704」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occaacti" runat="server" CssClass="NormalBold" Text="Occaacti"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occaacti" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occaacti」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occauser" runat="server" CssClass="NormalBold" Text="Occauser"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occauser" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occauser」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occagrup" runat="server" CssClass="NormalBold" Text="Occagrup"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occagrup" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occagrup」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occa1004" runat="server" CssClass="NormalBold" Text="Occa1004"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occa1004" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occa1004」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occaud15" runat="server" CssClass="NormalBold" Text="Occaud15"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occaud15" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occaud15」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0801" runat="server" CssClass="NormalBold" Text="Ta_occa0801"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0801" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0801」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0802" runat="server" CssClass="NormalBold" Text="Ta_occa0802"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0802" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0802」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0803" runat="server" CssClass="NormalBold" Text="Ta_occa0803"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0803" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0803」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0901" runat="server" CssClass="NormalBold" Text="Ta_occa0901"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0901" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0901」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0902" runat="server" CssClass="NormalBold" Text="Ta_occa0902"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0902" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0902」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa0903" runat="server" CssClass="NormalBold" Text="Ta_occa0903"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa0903" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa0903」!!" MaxLength="6"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa10" runat="server" CssClass="NormalBold" Text="Ta_occa10"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa10" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa10」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa11" runat="server" CssClass="NormalBold" Text="Ta_occa11"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa11" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa11」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa12" runat="server" CssClass="NormalBold" Text="Ta_occa12"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa12" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa12」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa14" runat="server" CssClass="NormalBold" Text="Ta_occa14"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa14" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa14」!!" MaxLength="1"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa15" runat="server" CssClass="NormalBold" Text="Ta_occa15"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa15" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa15」!!" MaxLength="10"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_ta_occa19" runat="server" CssClass="NormalBold" Text="Ta_occa19"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_ta_occa19" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Ta_occa19」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
 	 	 	 	 	<tr><td><asp:Label ID="LABEL_occanote" runat="server" CssClass="NormalBold" Text="Occanote"></asp:Label></td></tr><tr><td><SmoothEnterpriseWebControl:InputText id="FIELD_occanote" runat="server" BackColor="#F0F0F0" CssClass="Normal" ErrorMessage="Please Input「Occanote」!!" MaxLength="255"  ><Gradient GradientBegin="" GradientEnd="" GradientType="Top" /></SmoothEnterpriseWebControl:InputText></td></tr>
				</table>
			</td>
		</tr>
	</table>
	<table border="0" Class="Normal">
		<tr>
			<td>
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_save" runat="server" Text="儲存" width="80px" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_save_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>&nbsp;
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_savenext" runat="server" Text="儲存後繼續操作" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_save_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>&nbsp;
				<SmoothEnterpriseWebControl:InputButton ID="BUTTON_back" runat="server" Text="回上頁" width="80px" BackColor="#C8C8C8" BorderColor="#606060" BorderStyle="Solid" BorderWidth="1px" CssClass="NormalBold" Font-Bold="True" Font-Names="Arial" Font-Size="12px" OnClick="BUTTON_back_Click"><Gradient GradientBegin="136, 136, 136" GradientEnd="White" GradientType="Bottom" /></SmoothEnterpriseWebControl:InputButton>
			</td>
		</tr>
	</table>
</asp:Content>